global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'antispam-engine'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['antispam-engine:8080']
